In [30]:
!pip install numpy==2.2.0
!pip install pandas==2.2.3
!pip install scikit-learn==1.6.0
!pip install matplotlib==3.9.3

Requirement already satisfied: numpy==2.2.0 in c:\users\vickm\anaconda3\lib\site-packages (2.2.0)
Requirement already satisfied: pandas==2.2.3 in c:\users\vickm\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vickm\anaconda3\lib\site-packages (from pandas==2.2.3) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vickm\anaconda3\lib\site-packages (from pandas==2.2.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vickm\anaconda3\lib\site-packages (from pandas==2.2.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vickm\anaconda3\lib\site-packages (from pandas==2.2.3) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vickm\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.2.3) (1.17.0)
Requirement already satisfied: scikit-learn==1.6.0 in c:\users\vickm\anaconda3\lib\site-packages (1.6.0)
Requirement already satisfied: numpy>=1.19.5 in c:\users\vickm\anaconda3\lib\site-packages (from scikit-learn==1.6.0) (2.2.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\vickm\anaconda3\lib\site-packages (from scikit-learn==1.6.0) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\vickm\anaconda3\lib\site-packages (from scikit-learn==1.6.0) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\vickm\anaconda3\lib\site-packages (from scikit-learn==1.6.0) (3.5.0)
Requirement already satisfied: matplotlib==3.9.3 in c:\users\vickm\anaconda3\lib\site-packages (3.9.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (2.2.0)
Requirement already satisfied: packaging>=20.0 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vickm\anaconda3\lib\site-packages (from matplotlib==3.9.3) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\vickm\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib==3.9.3) (1.17.0)

In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [32]:
url= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%202/data/FuelConsumptionCo2.csv"

In [33]:
df=pd.read_csv(url)

In [34]:
# verify successful load with some randomly selected records
df.sample(1000)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
64,2014,AUDI,TT COUPE QUATTRO,SUBCOMPACT,2.0,4,A6,Z,10.4,7.6,9.1,31,209
850,2014,NISSAN,NV200 CARGO VAN,SPECIAL PURPOSE VEHICLE,2.0,4,AV,X,10.0,8.5,9.3,30,214
594,2014,JEEP,PATRIOT 4X4,SUV - SMALL,2.4,4,M5,X,10.3,8.4,9.4,30,216
917,2014,RAM,1500 FFV,PICKUP TRUCK - STANDARD,3.6,6,A8,X,13.9,9.5,11.9,24,274
375,2014,FORD,F150 FFV,PICKUP TRUCK - STANDARD,3.7,6,A6,X,14.0,10.3,12.3,23,283
...,...,...,...,...,...,...,...,...,...,...,...,...,...
782,2014,MINI,COOPER CONVERTIBLE,MINICOMPACT,1.6,4,A6,Z,8.7,6.6,7.8,36,179
481,2014,HONDA,ACCORD,MID-SIZE,2.4,4,AV,X,9.0,6.6,7.9,36,182
617,2014,KIA,RIO ECO,COMPACT,1.6,4,A6,X,8.5,6.4,7.6,37,175
911,2014,RAM,1500 4X4 (MDS),PICKUP TRUCK - STANDARD,5.7,8,A6,X,17.6,12.7,15.4,18,354
170,2014,CADILLAC,CTS SPORT WAGON,STATION WAGON - SMALL,3.6,6,AS6,X,13.3,8.9,11.3,25,260

In [35]:
df.describe()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [36]:
# visualization features
cdf = df[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_COMB','CO2EMISSIONS']]
cdf.sample(9)

     ENGINESIZE  CYLINDERS  FUELCONSUMPTION_COMB  CO2EMISSIONS
771         5.5          8                  12.7           292
382         5.0          8                  19.7           315
907         4.8          8                  12.8           294
702         1.5          4                   7.4           170
327         3.6          6                  16.5           264
82          2.0          4                   8.7           200
858         1.8          4                   7.8           179
373         3.5          6                  13.4           308
476         6.2          8                  22.1           354

In [ ]:
plt.scatter(cdf.FUELCONSUMPTION_COMB, cdf.CO2EMISSIONS,  color='blue')
plt.xlabel("FUELCONSUMPTION_COMB")
plt.ylabel("Emission")